# Generated by Django 5.1.1 on 2024-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_number', models.CharField(max_length=100)),
                ('phase_number', models.CharField(max_length=100)),
                ('search_text', models.CharField(max_length=100)),
            ],
        ),
    ]
